repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        stages: [pre-commit]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: trailing-whitespace
        stages: [pre-commit]
      - id: check-ast
        stages: [pre-commit]
      - id: check-toml
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.7
    hooks:
      - id: ruff
        args: ["--fix", "--show-source"]
        stages: [pre-commit]
  - repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
      - id: bandit
        files: semantix_agents/
        stages: [pre-commit]
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: 'v1.3.3'
    hooks:
      - id: python-safety-dependencies-check
        files: pyproject.toml
        args: ["--ignore=66051,65703"]
        stages: [pre-commit]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        files: semantix_agents/
        args: [--explicit-package-bases, --install-types, --non-interactive]
        additional_dependencies:
          - "langchain==0.1.6"
          - "chardet==5.2.0"
          - "pandas==2.2.2"
          - "restrictedpython==6.0"
          - "matplotlib==3.8.4"
        stages: [pre-commit]
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
